##### Util #####

# Change prefix from Ctrl b to Ctrl z
unbind C-b
set -g prefix C-s

# Send Ctrl z to terminal program
bind C-s send-prefix

# Increase scrollback history limit (default is 2000)
set -g history-limit 10000

# Enable mouse support (click to select panes, drag to resize)
set -g mouse on

# Reload config file and display a confirmation message
bind R source-file ~/.tmux.conf \; display-message "Tmux config reloaded!"

##### Windows #####

# Start window and pane numbering at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows when one is closed
set -g renumber-windows on

# New bindings
bind w new-window
bind l choose-tree -Zw
bind p last-window
bind Q kill-window
bind r command-prompt -I "#W" "rename-window '%%'"

##### Panes #####

# Split panes 
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Use Vim-style directional keys for pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# New bindings
bind-key q kill-pane

##### Statusline #####

# Position the status bar at the top instead of the bottom
set -g status-position top

# Set status bar format 
set -g status-style bg="#1e2030",fg="#cad3f5"
set -g window-status-format '#[bg=#363a4f] #I:#W #F '
set -g window-status-current-format '#[bg=#a6e3a1]#[fg=#40a02b] #I:#W #F '
# set -g window-status-current-format '#[bg=#a6e3a1]#[fg=#40a02b] #I #[bg=#40a02b]#[fg=#a6e3a1] #W #F '
set -g status-left ' #S '

# Right side clock display
set -g status-right "%I:%M:%S%p %d-%m-%Y "
set -g status-interval 1
