##### Util #####

# Change prefix from Ctrl b to Ctrl s
unbind C-b
set -g prefix C-s

# Send Ctrl z to terminal program
bind C-s send-prefix

# Increase scrollback history limit (default is 2000)
set -g history-limit 10000

# Enable mouse support (click to select panes, drag to resize)
set -g mouse on

# Reload config file and display a confirmation message
bind . source-file ~/.config/tmux/tmux.conf \; display-message "Tmux config reloaded!"

##### Sessions #####
bind L choose-tree -Zs
bind R command-prompt -I "#S" "rename-session '%%'"
bind N new-session
bind X confirm-before -p "Kill session #S? (y/n)" kill-session

##### Windows #####
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
bind n new-window
bind l choose-tree -Zw
bind p last-window
bind Q kill-window
bind r command-prompt -I "#W" "rename-window '%%'"
bind -r "<" swap-window -t -1    # move current window left
bind -r ">" swap-window -t +1    # move current window right

##### Panes #####
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind S-Left  swap-pane -s '{left-of}'
bind S-Down  swap-pane -s '{down-of}'
bind S-Up    swap-pane -s '{up-of}'
bind S-Right swap-pane -s '{right-of}'
bind q kill-pane

##### Statusline #####

# Position the status bar at the top instead of the bottom
set -g status-position top

# Set status bar format 
set -g status-style bg="#1e2030",fg="#cad3f5"
set -g window-status-separator ''
set -g window-status-current-format '#[bg=#a6da95]#[fg=#1e2030] #I #[bg=#2f4c39]#[fg=#cad3f5] #W#{?#F, #F,} '
set -g window-status-format '#[bg=#8aadf4]#[fg=#1e2030] #I #[bg=#303446]#[fg=#cad3f5] #W#{?#F, #F,} '
set -g status-left ' #S '

# Right side clock display
set -g status-right "%I:%M:%S%p %d-%m-%Y "
set -g status-interval 1
